### ISSUE TITLE
Missing items...?

### ISSUE THREAD

**Issue by bloodconfetti** [stal111/Compressed-Items#2]
![compressed missing](https://user-images.githubusercontent.com/53692357/62755972-4f6aab80-ba33-11e9-9fe4-d1cbca888bca.png)
Hi there, as per this github topic, I have no idea what's going on: VsnGamer/ElevatorMod#36 
[latest.log](https://github.com/stal111/Compressed-Items/files/3484867/latest.log)

If you can shed any light, it'd be much appreciated.

**Comment by ProsperCraft** [comment]
This is due to a breaking change in Forge .45 please update the mod or it breaks block registrations and nbt.

**Comment by bloodconfetti** [comment]
I believe I do have the latest version (compressed_items-1.14.4-1.0.jar) so long as I'm not misreading the files on CurseForge.

**Comment by stal111** [comment]
Fixed in compressed_items-1.14.4-1.1
