### ISSUE TITLE
[1.14.4] Feature request - Bamboo Blocks to be used as fuel in the furnace

### ISSUE THREAD

**Issue by Alexdami97** [stal111/Compressed-Items#4]
I tried using them in a furnace but they doesn't seem to be usable for it. It would be a really efficient way to use the bamboo blocks, so we don't have to decompress the blocks and be stuck with tons of stacks of bamboo items. I know it would be hard to translate the ratio of burned items from item to block but it would be a neat idea.

**Comment by stal111** [comment]
Added in 1.15-1.0
