### ISSUE TITLE
[Request] May I use the textures in another mod?

### ISSUE THREAD

**Issue by chimericdream** [stal111/Compressed-Items#6]
I have another mod that I have been working on, and I want to add storage blocks for things like carrots, potatoes, etc. I came across this mod and loved the textures you have. Since this mod hasn't been updated past 1.15, would it be alright if I use some of your textures in my mod? Obviously I would give full credit regarding which textures I used and where they came from.

Thanks!

**Comment by stal111** [comment]
Please contant me on Discord (Stal#1058) if you are still interested in using our textures.
